---
- name: Destroy the environment
  hosts: rhel9_servers
  become: true
  vars_files:
    - ./vars.yaml
  pre_tasks:
    - include_tasks: ../tasks/precondition_setup.yml
  tasks:
  - block:
    - include_tasks: ../tasks/status_update.yml
      vars:
        new_conditions:
        - type: "Destroyed"
          status: "False"
          reason: "DestroyNotReady"
          message: "Waiting for the destruction"
  
    - include_tasks: ../tasks/fault_removal.yml

    - include_tasks: ../tasks/user_remove.yml

    - include_tasks: ../tasks/status_update.yml
      vars:
        new_conditions:
        - type: "Deployed"
          status: "False"
          reason: "AlreadyDestroyed"
        - type: "FaultInjected"
          status: "False"
          reason: "AlreadyDestroyed"
        - type: "Destroyed"
          status: "True"

    rescue:
      - include_tasks: ../tasks/status_update.yml
        vars:
          new_conditions:
          - type: "Deployed"
            status: "True"
          - type: "FaultInjected"
            status: "True"
          - type: "Destroyed"
            status: "False"
            reason: "DestroyFailed"
            message: >
              Failed to destroy due to the following reason.
              The task "{{ ansible_failed_task.name }}" failed with error:
              {{ ansible_failed_result.msg }}

      - name: Show full details of the failed task
        debug:
          var: ansible_failed_result